### ISSUE TITLE
Poor site accessibility

### ISSUE THREAD

**Issue by Derpius** [Fasteroid/svelte-portfolio#1]
Raising as a dedicated issue from https://github.com/Fasteroid/react-portfolio/issues/1 as it's more severe than I initially thought

- Without client-side javascript, the site is completely unnavigable as the navbar does not render
- The raytracing page is essentially impossible to use with a screen reader, as there are a number of buttons which have no visual or accessible labels
- There are a number of other a11y issues that flag when using Axe or Chrome Lighthouse tests
- Semantic HTML does not seem to have been used on any page:
  - The visual page headings do not use h tags
  - The navbar does not use the semantic [nav](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) element
  - Etc.

I haven't run the page with a screen reader, but I recommend testing with NVDA and Chrome for Windows and then VoiceOver and Safari on iOS and macOS

**Comment by Derpius** [comment]
This is a great guide for learning semantic HTML usage: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML

**Comment by Fasteroid** [comment]
Thanks for the info, semantic html tune-ups are on my todo list.  I'm already aware of the issue with the navbar—this will be properly fixed when I rewrite the site.

**Comment by Fasteroid** [comment]
Closing this now since most of these problems are fixed now.  

The raytracer gallery is still questionable in terms of accessibility, but I argue that if you're blind enough to need a screen reader to navigate, the entire point of that page is lost anyway and hence accessibility is no-longer a concern.
